version: '3'

networks:
  monitor:

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env.development
    depends_on:
      - redis
    volumes:
      - ./backend/:/backend/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitor

  redis:
    image: redis
    networks:
      - monitor

volumes:
  redis:
